version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=lab2db
      - POSTGRES_USER=labuser
      - POSTGRES_PASSWORD=labpass
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lab2db
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
