services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata initial_data.json &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lab2db
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "labuser", "-d", "lab2db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
