@startuml vue-deploiement-simplifiee
title Vue de Déploiement - Environnement local

skinparam linetype ortho
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

node "Poste de l'Utilisateur" as dev {
  node "Navigateur Web" as browser
}

node "Serveur (Docker Host)" as docker_host {
  node "Conteneur Web (Django)" as container_web {
    component app_django as "Application Django"
  }

  node "Conteneur BD (PostgreSQL)" as container_db {
    component db_postgres as "Base de données PostgreSQL"
  }

  app_django --> db_postgres : ORM (psycopg2)
}

browser -right-> app_django : Requêtes HTTP

@enduml
