name: CI/CD Pipeline - LOG430 Lab2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: lab2db
          POSTGRES_USER: labuser
          POSTGRES_PASSWORD: labpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U labuser -d lab2db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: lab2db
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      DB_HOST: localhost         
      DB_PORT: 5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until pg_isready -h localhost -p 5432 -U labuser; do sleep 1; done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run unit + integration tests
        run: pytest tests/

      - name: Check code formatting with Black
        run: black --check . --exclude '/migrations/'

      - name: Build Docker image
        run: docker build -t docker.io/talipkoyluoglu/log430-lab2:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push docker.io/talipkoyluoglu/log430-lab2:latest
